apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
configMapGenerator:
  - name: someconfig
    behavior: merge
    files:
      - bar=files/bar.json
    literals:
      - baz=qux
